# Generated by Django 5.2.7 on 2025-10-13 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuetrack.problem')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuetrack.solution')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='problems',
            field=models.ManyToManyField(through='valuetrack.SolutionProblem', to='valuetrack.problem'),
        ),
        migrations.CreateModel(
            name='SupplierSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuetrack.solution')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuetrack.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='suppliers',
            field=models.ManyToManyField(through='valuetrack.SupplierSolution', to='valuetrack.supplier'),
        ),
    ]
