# Generated by Django 5.2.7 on 2025-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersolution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
