# Generated by Django 5.2.7 on 2025-10-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0003_trackuparea'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('assets', 'Assets'), ('services', 'Services'), ('spend', 'Spend'), ('income', 'Income'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuetrack.solution')),
            ],
        ),
        migrations.DeleteModel(
            name='TrackUpArea',
        ),
    ]
